= Dedicated Portal

image:https://travis-ci.org/container-mgmt/dedicated-portal.svg?branch=master["Build Status", link="https://travis-ci.org/container-mgmt/dedicated-portal"]

This package provides an application that simplifies the creation and
management of OpenShift clusters.

== Building

To build the project clone the repository in any directory and run the
`make` command.

To build the container images run the `make images` command.

== Deploying

To deploy the application to an OpenShift cluster you will first need to
build the images and upload them to the image registry used by the
cluster. The images can be built and exported to `.tar` files files with
the `make tars` command:

```
$ make tars
$ ls *.tar | sort
dedicated-portal_clusters-service_0.0.0.tar
dedicated-portal_customers-service_0.0.0.tar
dedicated-portal_customers-portal.0.0.tar
dedicated-portal_messaging-service_0.0.0.tar
```

Those `.tar` files can then be copied to the OpenShirt cluster, and
uploaded to the image registry:

```
$ scp *.tar myhost:.
$ ssh root@myhost
# docker load -i dedicated-portal_clusters-service_0.0.0.tar
# docker load -i dedicated-portal_customers-service_0.0.0.tar
# docker load -i dedicated-portal_customers-portal.0.0.tar
# docker load -i dedicated-portal_messaging-service_0.0.0.tar
```

Then the `template.sh` script can be used to create and populate the
`dedicated-portal` namespace:

```
$ ./template.sh
$ oc get pods -n dedicated-portal
NAME                                READY  STATUS   RESTARTS  AGE
clusters-db-59dbb97d4f-qdmjw        1/1    Running  0         1m
clusters-service-6b4877b885-k7zg2   1/1    Running  0         1m
customers-db-6cc7fc8c49-7mh7t       1/1    Running  0         1m
customers-portal-8474a9d5b7-6j1qt   1/1    Running  0         1m
customers-service-7dfdf5b6b5-hqznw  1/1    Running  0         1m
messaging-service-7474b9d5b7-6n2qt  1/1    Running  0         1m
```

To undeploy the application remove the `dedicated-portal` namespace:

```
$ oc delete namespace dedicated-portal
```
