= Dedicated Portal

image:https://travis-ci.org/container-mgmt/dedicated-portal.svg?branch=master["Build Status", link="https://travis-ci.org/container-mgmt/dedicated-portal"]

This package provides an application that simplifies the creation and
management of _OpenShift_ clusters.

== Building

To build the project clone the repository into your `GOPATH` and run the
`make` command.

To build the container images run the `make images` command.

== Deploying to an existing cluster

To deploy the application to an _OpenShift_ cluster you will first need to
build the images and upload them to the image registry used by the
cluster. The images can be built and exported to `.tar` files files with
the `make tars` command:

[source]
----
$ make tars
$ ls *.tar | sort
dedicated-portal_clusters-service_latest.tar
dedicated-portal_customers-service_latest.tar
----

Those `.tar` files can then be copied to the _OpenShift_ cluster, and
uploaded to the image registry:

[source]
----
$ scp *.tar template.* myhost:.
$ ssh root@myhost
# docker load -i dedicated-portal_clusters-service_latest.tar
# docker load -i dedicated-portal_customers-service_latest.tar
----

Then the `template.sh` script can be used to create and populate the
`dedicated-portal` namespace:

[source]
----
$ ./template.sh
$ oc get pods -n dedicated-portal
NAME                                READY  STATUS   RESTARTS  AGE
clusters-db-59dbb97d4f-qdmjw        1/1    Running  0         1m
clusters-service-6b4877b885-k7zg2   1/1    Running  0         1m
customers-db-6cc7fc8c49-7mh7t       1/1    Running  0         1m
customers-service-7dfdf5b6b5-hqznw  1/1    Running  0         1m
----

To undeploy the application remove the `dedicated-portal` namespace:

[source]
----
$ oc delete namespace dedicated-portal
----

== Deploying using oc cluster up

=== Fedora

Install and setup Docker:

[source]
----
sudo dnf install docker
sudo systemctl start docker
----

Install and setup origin-clients:

[source]
----
dnf install origin-clients
----

Edit the `/etc/containers/registries.conf` file and add the following lines:

[source]
----
[registries.insecure]
registries = ['172.30.0.0/16']
----

Run:

[source]
----
./hack/cluster-restart.sh
----
